from dataclasses import dataclass

@dataclass
class SymbolDescription:
	name: str
	offset: int
	description: str

SYMBOL_DESCRIPTIONS = [
	SymbolDescription('CP', 0xFE10, 'Context Pointer'),
	SymbolDescription('CSP', 0xFE08, 'Code Segment Pointer'),
	SymbolDescription('PSW', 0xFF10, 'Processor Status Word'),
	SymbolDescription('SP', 0xFE12, 'Stack Pointer'),
	SymbolDescription('STKOV', 0xFE14, 'Stack Overflow register'),
	SymbolDescription('STKUN', 0xFE16, 'Stack Underflow register'),
	SymbolDescription('DPP0', 0xFE00, 'Data Page Pointer 0'),
	SymbolDescription('DPP1', 0xFE02, 'Data Page Pointer 1'),
	SymbolDescription('DPP2', 0xFE04, 'Data Page Pointer 2'),
	SymbolDescription('DPP3', 0xFE06, 'Data Page Pointer 3'),
	SymbolDescription('MDH', 0xFE0C, 'Multiply/Divide register High'),
	SymbolDescription('MDL', 0xFE0E, 'Multiply/Divide register Low'),
	SymbolDescription('MDC', 0xFF0E, 'Multiply/Divide Control register'),
	SymbolDescription('SYSCON', 0xFF12, 'System Configuration register'),
	SymbolDescription('TFR', 0xFFAC, 'Trap Flag Register'),
	SymbolDescription('EXICON', 0xF1C0, 'External Interrupt Control register'),
	SymbolDescription('EXISEL', 0xF1DA, 'External Interrupt Select register'),
	SymbolDescription('ADDRSEL1', 0xFE18, 'Address1 Range Select register'),
	SymbolDescription('ADDRSEL2', 0xFE1A, 'Address2 Range Select register'),
	SymbolDescription('ADDRSEL3', 0xFE1C, 'Address3 Range Select register'),
	SymbolDescription('ADDRSEL4', 0xFE1E, 'Address4 Range Select register'),
	SymbolDescription('BUSCON0', 0xFF0C, 'Bus0 Mode Control register'),
	SymbolDescription('BUSCON1', 0xFF14, 'Bus1 Mode Control register'),
	SymbolDescription('BUSCON2', 0xFF16, 'Bus2 Mode Control register'),
	SymbolDescription('BUSCON3', 0xFF18, 'Bus3 Mode Control register'),
	SymbolDescription('BUSCON4', 0xFF1A, 'Bus4 Mode Control register'),
	SymbolDescription('PECC0', 0xFEC0, 'Periphal Event Controller 0 Control register'),
	SymbolDescription('PECC1', 0xFEC2, 'Periphal Event Controller 1 Control register'),
	SymbolDescription('PECC2', 0xFEC4, 'Periphal Event Controller 2 Control register'),
	SymbolDescription('PECC3', 0xFEC6, 'Periphal Event Controller 3 Control register'),
	SymbolDescription('PECC4', 0xFEC8, 'Periphal Event Controller 4 Control register'),
	SymbolDescription('PECC5', 0xFECA, 'Periphal Event Controller 5 Control register'),
	SymbolDescription('PECC6', 0xFECC, 'Periphal Event Controller 6 Control register'),
	SymbolDescription('PECC7', 0xFECE, 'Periphal Event Controller 7 Control register'),
	SymbolDescription('SRCP0', 0xFCE0, 'Periphal Event Controller 0 Source Pointer'),
	SymbolDescription('DSTP0', 0xFCE2, 'Periphal Event Controller 0 Destination Pointer'),
	SymbolDescription('SRCP1', 0xFCE4, 'Periphal Event Controller 1 Source Pointer'),
	SymbolDescription('DSTP1', 0xFCE6, 'Periphal Event Controller 1 Destination Pointer'),
	SymbolDescription('SRCP2', 0xFCE8, 'Periphal Event Controller 2 Source Pointer'),
	SymbolDescription('DSTP2', 0xFCEA, 'Periphal Event Controller 2 Destination Pointer'),
	SymbolDescription('SRCP3', 0xFCEC, 'Periphal Event Controller 3 Source Pointer'),
	SymbolDescription('DSTP3', 0xFCEE, 'Periphal Event Controller 3 Destination Pointer'),
	SymbolDescription('SRCP4', 0xFCF0, 'Periphal Event Controller 4 Source Pointer'),
	SymbolDescription('DSTP4', 0xFCF2, 'Periphal Event Controller 4 Destination Pointer'),
	SymbolDescription('SRCP5', 0xFCF4, 'Periphal Event Controller 5 Source Pointer'),
	SymbolDescription('DSTP5', 0xFCF6, 'Periphal Event Controller 5 Destination Pointer'),
	SymbolDescription('SRCP6', 0xFCF8, 'Periphal Event Controller 6 Source Pointer'),
	SymbolDescription('DSTP6', 0xFCFA, 'Periphal Event Controller 6 Destination Pointer'),
	SymbolDescription('SRCP7', 0xFCFC, 'Periphal Event Controller 7 Source Pointer'),
	SymbolDescription('DSTP7', 0xFCFE, 'Periphal Event Controller 7 Destination Pointer'),
	SymbolDescription('P0L', 0xFF00, 'Port 0 Data register Low'),
	SymbolDescription('P0H', 0xFF02, 'Port 0 Data register High'),
	SymbolDescription('DP0L', 0xF100, 'Port 0 Direction register Low'),
	SymbolDescription('DP0H', 0xF102, 'Port 0 Direction register High'),
	SymbolDescription('P1L', 0xFF04, 'Port 1 Data register Low'),
	SymbolDescription('P1H', 0xFF06, 'Port 1 Data register High'),
	SymbolDescription('DP1L', 0xF104, 'Port 1 Direction register Low'),
	SymbolDescription('DP1H', 0xF106, 'Port 1 Direction register High'),
	SymbolDescription('P2', 0xFFC0, 'Port 2 Data register'),
	SymbolDescription('DP2', 0xFFC2, 'Port 2 Direction register'),
	SymbolDescription('ODP2', 0xF1C2, 'Port 2 Open Drain control register'),
	SymbolDescription('P3', 0xFFC4, 'Port 3 Data register'),
	SymbolDescription('DP3', 0xFFC6, 'Port 3 Direction register'),
	SymbolDescription('ODP3', 0xF1C6, 'Port 3 Open Drain control register'),
	SymbolDescription('P4', 0xFFC8, 'Port 4 Data register'),
	SymbolDescription('DP4', 0xFFCA, 'Port 4 Direction register'),
	SymbolDescription('ODP4', 0xF1CA, 'Port 4 Open Drain control register'),
	SymbolDescription('P5', 0xFFA2, 'Port 5 Data register'),
	SymbolDescription('P6', 0xFFCC, 'Port 6 Data register'),
	SymbolDescription('DP6', 0xFFCE, 'Port 6 Direction register'),
	SymbolDescription('ODP6', 0xF1CE, 'Port 6 Open Drain control register'),
	SymbolDescription('P7', 0xFFD0, 'Port 7 Data register'),
	SymbolDescription('DP7', 0xFFD2, 'Port 7 Direction register'),
	SymbolDescription('ODP7', 0xF1D2, 'Port 7 Open Drain control register'),
	SymbolDescription('P8', 0xFFD4, 'Port 8 Data register'),
	SymbolDescription('DP8', 0xFFD6, 'Port 8 Direction register'),
	SymbolDescription('ODP8', 0xF1D6, 'Port 8 Open Drain control register'),
	SymbolDescription('RP0H', 0xF108, 'Port 0H Reset Configuration register'),
	SymbolDescription('CAPREL', 0xFE4A, 'Capture Reload register'),
	SymbolDescription('CRIC', 0xFF6A, 'CAPREL Interrupt Control register'),
	SymbolDescription('T01CON', 0xFF50, 'CAPCOM1 Timers T0 and T1 Control Register'),
	SymbolDescription('T0', 0xFE50, 'CAPCOM Timer 0 register'),
	SymbolDescription('T1', 0xFE52, 'CAPCOM Timer 1 register'),
	SymbolDescription('T0IC', 0xFF9C, 'CAPCOM Timer 0 Interrupt Control register'),
	SymbolDescription('T1IC', 0xFF9E, 'CAPCOM Timer 1 Interrupt Control register'),
	SymbolDescription('T0REL', 0xFE54, 'CAPCOM Timer 0 Reload register'),
	SymbolDescription('T1REL', 0xFE56, 'CAPCOM Timer 1 Reload register'),
	SymbolDescription('T78CON', 0xFF20, 'CAPCOM1 Timers T7 and T8 Control Register'),
	SymbolDescription('T7', 0xF050, 'CAPCOM Timer 7 register'),
	SymbolDescription('T8', 0xF052, 'CAPCOM Timer 8 register'),
	SymbolDescription('T7IC', 0xF17A, 'CAPCOM Timer 7 Interrupt Control register'),
	SymbolDescription('T8IC', 0xF17C, 'CAPCOM Timer 8 Interrupt Control register'),
	SymbolDescription('T7REL', 0xF054, 'CAPCOM Timer 7 Reload register'),
	SymbolDescription('T8REL', 0xF056, 'CAPCOM Timer 8 Reload register'),
	SymbolDescription('T2', 0xFE40, 'CAPCOM Timer 2 register'),
	SymbolDescription('T2CON', 0xFF40, 'CAPCOM Timer 2 Control register'),
	SymbolDescription('T3', 0xFE42, 'CAPCOM Timer 3 register'),
	SymbolDescription('T3CON', 0xFF42, 'CAPCOM Timer 3 Control register'),
	SymbolDescription('T4', 0xFE44, 'CAPCOM Timer 4 register'),
	SymbolDescription('T4CON', 0xFF44, 'CAPCOM Timer 4 Control register'),
	SymbolDescription('T5', 0xFE46, 'CAPCOM Timer 5 register'),
	SymbolDescription('T5CON', 0xFF46, 'CAPCOM Timer 5 Control register'),
	SymbolDescription('T6', 0xFE48, 'CAPCOM Timer 6 register'),
	SymbolDescription('T6CON', 0xFF48, 'CAPCOM Timer 6 Control register'),
	SymbolDescription('T2IC', 0xFF60, 'CAPCOM Timer 2 Interrupt Control register'),
	SymbolDescription('T3IC', 0xFF62, 'CAPCOM Timer 3 Interrupt Control register'),
	SymbolDescription('T4IC', 0xFF64, 'CAPCOM Timer 4 Interrupt Control register'),
	SymbolDescription('T5IC', 0xFF66, 'CAPCOM Timer 5 Interrupt Control register'),
	SymbolDescription('T6IC', 0xFF68, 'CAPCOM Timer 6 Interrupt Control register'),
	SymbolDescription('WDT', 0xFEAE, 'Watch Dog Timer'),
	SymbolDescription('WDTCON', 0xFFAE, 'Watch Dog Timer Control register'),
	SymbolDescription('S0TBUF', 0xFEB0, 'ASC0 Transmit Buffer register'),
	SymbolDescription('S0RBUF', 0xFEB2, 'ASC0 Receive Buffer register'),
	SymbolDescription('S0BG', 0xFEB4, 'ASC0 Baud Rate Generator/Reload register'),
	SymbolDescription('S0TIC', 0xFF6C, 'ASC0 Transmit Interrupt Control register'),
	SymbolDescription('S0RIC', 0xFF6E, 'ASC0 Receive Interrupt Control register'),
	SymbolDescription('S0EIC', 0xFF70, 'ASC0 Error Interrupt Control register'),
	SymbolDescription('S0TBIC', 0xF19C, 'ASC0 Transmit Buffer Interrupt Control register'),
	SymbolDescription('S0CON', 0xFFB0, 'ASC0 Control register'),
	SymbolDescription('SSCCON', 0xFFB2, 'SSC Control register'),
	SymbolDescription('SSCTIC', 0xFF72, 'SSC Transmit Interrupt Control register'),
	SymbolDescription('SSCRIC', 0xFF74, 'SSC Receive Interrupt Control register'),
	SymbolDescription('SSCEIC', 0xFF76, 'SSC Error Interrupt Control register'),
	SymbolDescription('SSCBR', 0xF0B4, 'SSC Baud Rate Generator/Reload register'),
	SymbolDescription('SSCRB', 0xF0B2, 'SSC Receive Buffer register'),
	SymbolDescription('SSCTB', 0xF0B0,  'SSC Transmit Buffer register'),
	SymbolDescription('CC0', 0xFE80, 'CAPCOM0 register'),
	SymbolDescription('CC1', 0xFE82, 'CAPCOM1 register'),
	SymbolDescription('CC2', 0xFE84, 'CAPCOM2 register'),
	SymbolDescription('CC3', 0xFE86, 'CAPCOM3 register'),
	SymbolDescription('CC4', 0xFE88, 'CAPCOM4 register'),
	SymbolDescription('CC5', 0xFE8A, 'CAPCOM5 register'),
	SymbolDescription('CC6', 0xFE8C, 'CAPCOM6 register'),
	SymbolDescription('CC7', 0xFE8E, 'CAPCOM7 register'),
	SymbolDescription('CC8', 0xFE90, 'CAPCOM8 register'),
	SymbolDescription('CC9', 0xFE92, 'CAPCOM9 register'),
	SymbolDescription('CC10', 0xFE94, 'CAPCOM10 register'),
	SymbolDescription('CC11', 0xFE96, 'CAPCOM11 register'),
	SymbolDescription('CC12', 0xFE98, 'CAPCOM12 register'),
	SymbolDescription('CC13', 0xFE9A, 'CAPCOM13 register'),
	SymbolDescription('CC14', 0xFE9C, 'CAPCOM14 register'),
	SymbolDescription('CC15', 0xFE9E, 'CAPCOM15 register'),
	SymbolDescription('CC16', 0xFE60, 'CAPCOM16 register'),
	SymbolDescription('CC17', 0xFE62, 'CAPCOM17 register'),
	SymbolDescription('CC18', 0xFE64, 'CAPCOM18 register'),
	SymbolDescription('CC19', 0xFE66, 'CAPCOM19 register'),
	SymbolDescription('CC20', 0xFE68, 'CAPCOM20 register'),
	SymbolDescription('CC21', 0xFE6A, 'CAPCOM21 register'),
	SymbolDescription('CC22', 0xFE6C, 'CAPCOM22 register'),
	SymbolDescription('CC23', 0xFE6E, 'CAPCOM23 register'),
	SymbolDescription('CC24', 0xFE70, 'CAPCOM24 register'),
	SymbolDescription('CC25', 0xFE72, 'CAPCOM25 register'),
	SymbolDescription('CC26', 0xFE74, 'CAPCOM26 register'),
	SymbolDescription('CC27', 0xFE76, 'CAPCOM27 register'),
	SymbolDescription('CC28', 0xFE78, 'CAPCOM28 register'),
	SymbolDescription('CC29', 0xFE7A, 'CAPCOM29 register'),
	SymbolDescription('CC30', 0xFE7C, 'CAPCOM30 register'),
	SymbolDescription('CC31', 0xFE7E, 'CAPCOM31 register'),
	SymbolDescription('CC0IC', 0xFF78, 'CAPCOM0 Interrupt Control register'),
	SymbolDescription('CC1IC', 0xFF7A, 'CAPCOM1 Interrupt Control register'),
	SymbolDescription('CC2IC', 0xFF7C, 'CAPCOM2 Interrupt Control register'),
	SymbolDescription('CC3IC', 0xFF7E, 'CAPCOM3 Interrupt Control register'),
	SymbolDescription('CC4IC', 0xFF80, 'CAPCOM4 Interrupt Control register'),
	SymbolDescription('CC5IC', 0xFF82, 'CAPCOM5 Interrupt Control register'),
	SymbolDescription('CC6IC', 0xFF84, 'CAPCOM6 Interrupt Control register'),
	SymbolDescription('CC7IC', 0xFF86, 'CAPCOM7 Interrupt Control register'),
	SymbolDescription('CC8IC', 0xFF88, 'CAPCOM8 Interrupt Control register'),
	SymbolDescription('CC9IC', 0xFF8A, 'CAPCOM9 Interrupt Control register'),
	SymbolDescription('CC10IC', 0xFF8C, 'CAPCOM10 Interrupt Control register'),
	SymbolDescription('CC11IC', 0xFF8E, 'CAPCOM11 Interrupt Control register'),
	SymbolDescription('CC12IC', 0xFF90, 'CAPCOM12 Interrupt Control register'),
	SymbolDescription('CC13IC', 0xFF92, 'CAPCOM13 Interrupt Control register'),
	SymbolDescription('CC14IC', 0xFF94, 'CAPCOM14 Interrupt Control register'),
	SymbolDescription('CC15IC', 0xFF96, 'CAPCOM15 Interrupt Control register'),
	SymbolDescription('CC16IC', 0xF160, 'CAPCOM16 Interrupt Control register'),
	SymbolDescription('CC17IC', 0xF162, 'CAPCOM17 Interrupt Control register'),
	SymbolDescription('CC18IC', 0xF164, 'CAPCOM18 Interrupt Control register'),
	SymbolDescription('CC19IC', 0xF166, 'CAPCOM19 Interrupt Control register'),
	SymbolDescription('CC20IC', 0xF168, 'CAPCOM20 Interrupt Control register'),
	SymbolDescription('CC21IC', 0xF16A, 'CAPCOM21 Interrupt Control register'),
	SymbolDescription('CC22IC', 0xF16C, 'CAPCOM22 Interrupt Control register'),
	SymbolDescription('CC23IC', 0xF16E, 'CAPCOM23 Interrupt Control register'),
	SymbolDescription('CC24IC', 0xF170, 'CAPCOM24 Interrupt Control register'),
	SymbolDescription('CC25IC', 0xF172, 'CAPCOM25 Interrupt Control register'),
	SymbolDescription('CC26IC', 0xF174, 'CAPCOM26 Interrupt Control register'),
	SymbolDescription('CC27IC', 0xF176, 'CAPCOM27 Interrupt Control register'),
	SymbolDescription('CC28IC', 0xF178, 'CAPCOM28 Interrupt Control register'),
	SymbolDescription('CC29IC', 0xF184, 'CAPCOM29 Interrupt Control register'),
	SymbolDescription('CC30IC', 0xF18C, 'CAPCOM30 Interrupt Control register'),
	SymbolDescription('CC31IC', 0xF194, 'CAPCOM31 Interrupt Control register'),
	SymbolDescription('CCM0', 0xFF52, 'CAPCOM0 Mode Control register'),
	SymbolDescription('CCM1', 0xFF54, 'CAPCOM1 Mode Control register'),
	SymbolDescription('CCM2', 0xFF56, 'CAPCOM2 Mode Control register'),
	SymbolDescription('CCM3', 0xFF58, 'CAPCOM3 Mode Control register'),
	SymbolDescription('CCM4', 0xFF22, 'CAPCOM4 Mode Control register'),
	SymbolDescription('CCM5', 0xFF24, 'CAPCOM5 Mode Control register'),
	SymbolDescription('CCM6', 0xFF26, 'CAPCOM6 Mode Control register'),
	SymbolDescription('CCM7', 0xFF28, 'CAPCOM7 Mode Control register'),
	SymbolDescription('PWMCON0', 0xFF30, 'PWM0 Control register'),
	SymbolDescription('PWMCON1', 0xFF32, 'PWM1 Control register'),
	SymbolDescription('PWMIC', 0xF17E, 'PWM Interrupt Control register'),
	SymbolDescription('PP0', 0xF038, 'PWM0 Period register'),
	SymbolDescription('PP1', 0xF03A, 'PWM1 Period register'),
	SymbolDescription('PP2', 0xF03C, 'PWM2 Period register'),
	SymbolDescription('PP3', 0xF03E, 'PWM3 Period register'),
	SymbolDescription('PT0', 0xF030, 'PWM0 Counter register'),
	SymbolDescription('PT1', 0xF032, 'PWM1 Counter register'),
	SymbolDescription('PT2', 0xF034, 'PWM2 Counter register'),
	SymbolDescription('PT3', 0xF036, 'PWM3 Counter register'),
	SymbolDescription('PW0', 0xFE30, 'PWM0 Pulse Width register'),
	SymbolDescription('PW1', 0xFE32, 'PWM1 Pulse Width register'),
	SymbolDescription('PW2', 0xFE34, 'PWM2 Pulse Width register'),
	SymbolDescription('PW3', 0xFE36, 'PWM3 Pulse Width register'),
	SymbolDescription('ADCON', 0xFFA0, 'A/D Converter Control register'),
	SymbolDescription('ADDAT', 0xFEA0, 'A/D Converter Result register'),
	SymbolDescription('ADDAT2', 0xF0A0, 'A/D Converter Channel Injection Result register'),
	SymbolDescription('ADCIC', 0xFF98, 'A/D Converter Interrupt Control register (End of Conversion)'),
	SymbolDescription('ADEIC', 0xFF9A, 'A/D Converter Interrupt Control register (Overrun Error / Channel Injection)'),
	SymbolDescription('XP0IC', 0xF186, 'X-Peripheral 0 Interrupt Control register'),
	SymbolDescription('XP1IC', 0xF18E, 'X-Peripheral 1 Interrupt Control register'),
	SymbolDescription('XP2IC', 0xF196, 'X-Peripheral 2 Interrupt Control register'),
	SymbolDescription('XP3IC', 0xF19E, 'X-Peripheral 3 Interrupt Control register'),
	SymbolDescription('C1BTR', 0xEF04, 'CAN1 Bit Timing Register'),
	SymbolDescription('C1CSR', 0xEF00, 'CAN1 Control/Status Register'),
	SymbolDescription('C1GMS', 0xEF06, 'CAN1 Global Mask Short'),
	SymbolDescription('C1IR', 0xEF02, 'CAN1 Interrupt Register'),
	SymbolDescription('C1LGML', 0xEF0A, 'CAN1 Lower Global Mask Long'),
	SymbolDescription('C1LMLM', 0xEF0E, 'CAN1 Lower Mask of Last Message'),
	SymbolDescription('C1UGML', 0xEF08, 'CAN1 Upper Global Mask Long'),
	SymbolDescription('C1UMLM', 0xEF0C, 'CAN1 Upper Mask of Last Message'),
	SymbolDescription('C1MCR1', 0xEF10, 'CAN1 Message1 Control Register'),
	SymbolDescription('C1AR1', 0xEF12, 'CAN1 Message1 Upper Arbitration Register'),
	SymbolDescription('C1LAR1', 0xEF14, 'CAN1 Message1 Lower Arbitration Register'),
	SymbolDescription('C1MCFG1', 0xEF16, 'CAN1 Message1 Configuration Register'),
	SymbolDescription('C1MCR2', 0xEF20, 'CAN1 Message2 Control Register'),
	SymbolDescription('C1AR2', 0xEF22, 'CAN1 Message2 Upper Arbitration Register'),
	SymbolDescription('C1LAR2', 0xEF24, 'CAN1 Message2 Lower Arbitration Register'),
	SymbolDescription('C1MCFG2', 0xEF26, 'CAN1 Message2 Configuration Register'),
	SymbolDescription('C1MCR3', 0xEF30, 'CAN1 Message3 Control Register'),
	SymbolDescription('C1AR3', 0xEF32, 'CAN1 Message3 Upper Arbitration Register'),
	SymbolDescription('C1LAR3', 0xEF34, 'CAN1 Message3 Lower Arbitration Register'),
	SymbolDescription('C1MCFG3', 0xEF36, 'CAN1 Message3 Configuration Register'),
	SymbolDescription('C1MCR4', 0xEF40, 'CAN1 Message4 Control Register'),
	SymbolDescription('C1AR4', 0xEF42, 'CAN1 Message4 Upper Arbitration Register'),
	SymbolDescription('C1LAR4', 0xEF44, 'CAN1 Message4 Lower Arbitration Register'),
	SymbolDescription('C1MCFG4', 0xEF46, 'CAN1 Message4 Configuration Register'),
	SymbolDescription('C1MCR5', 0xEF50, 'CAN1 Message5 Control Register'),
	SymbolDescription('C1AR5', 0xEF52, 'CAN1 Message5 Upper Arbitration Register'),
	SymbolDescription('C1LAR5', 0xEF54, 'CAN1 Message5 Lower Arbitration Register'),
	SymbolDescription('C1MCFG5', 0xEF56, 'CAN1 Message5 Configuration Register'),
	SymbolDescription('C1MCR6', 0xEF60, 'CAN1 Message6 Control Register'),
	SymbolDescription('C1AR6', 0xEF62, 'CAN1 Message6 Upper Arbitration Register'),
	SymbolDescription('C1LAR6', 0xEF64, 'CAN1 Message6 Lower Arbitration Register'),
	SymbolDescription('C1MCFG6', 0xEF66, 'CAN1 Message6 Configuration Register'),
	SymbolDescription('C1MCR7', 0xEF70, 'CAN1 Message7 Control Register'),
	SymbolDescription('C1AR7', 0xEF72, 'CAN1 Message7 Upper Arbitration Register'),
	SymbolDescription('C1LAR7', 0xEF74, 'CAN1 Message7 Lower Arbitration Register'),
	SymbolDescription('C1MCFG7', 0xEF76, 'CAN1 Message7 Configuration Register'),
	SymbolDescription('C1MCR8', 0xEF80, 'CAN1 Message8 Control Register'),
	SymbolDescription('C1AR8', 0xEF82, 'CAN1 Message8 Upper Arbitration Register'),
	SymbolDescription('C1LAR8', 0xEF84, 'CAN1 Message8 Lower Arbitration Register'),
	SymbolDescription('C1MCFG8', 0xEF86, 'CAN1 Message8 Configuration Register'),
	SymbolDescription('C1MCR9', 0xEF90, 'CAN1 Message9 Control Register'),
	SymbolDescription('C1AR9', 0xEF92, 'CAN1 Message9 Upper Arbitration Register'),
	SymbolDescription('C1LAR9', 0xEF94, 'CAN1 Message9 Lower Arbitration Register'),
	SymbolDescription('C1MCFG9', 0xEF96, 'CAN1 Message9 Configuration Register'),
	SymbolDescription('C1MCR10', 0xEFA0, 'CAN1 Message10 Control Register'),
	SymbolDescription('C1AR10', 0xEFA2, 'CAN1 Message10 Upper Arbitration Register'),
	SymbolDescription('C1LAR10', 0xEFA4, 'CAN1 Message10 Lower Arbitration Register'),
	SymbolDescription('C1MCFG10', 0xEFA6, 'CAN1 Message10 Configuration Register'),
	SymbolDescription('C1MCR11', 0xEFB0, 'CAN1 Message11 Control Register'),
	SymbolDescription('C1AR11', 0xEFB2, 'CAN1 Message11 Upper Arbitration Register'),
	SymbolDescription('C1LAR11', 0xEFB4, 'CAN1 Message11 Lower Arbitration Register'),
	SymbolDescription('C1MCFG11', 0xEFB6, 'CAN1 Message11 Configuration Register'),
	SymbolDescription('C1MCR12', 0xEFC0, 'CAN1 Message12 Control Register'),
	SymbolDescription('C1AR12', 0xEFC2, 'CAN1 Message12 Upper Arbitration Register'),
	SymbolDescription('C1LAR12', 0xEFC4, 'CAN1 Message12 Lower Arbitration Register'),
	SymbolDescription('C1MCFG12', 0xEFC6, 'CAN1 Message12 Configuration Register'),
	SymbolDescription('C1MCR13', 0xEFD0, 'CAN1 Message13 Control Register'),
	SymbolDescription('C1AR13', 0xEFD2, 'CAN1 Message13 Upper Arbitration Register'),
	SymbolDescription('C1LAR13', 0xEFD4, 'CAN1 Message13 Lower Arbitration Register'),
	SymbolDescription('C1MCFG13', 0xEFD6, 'CAN1 Message13 Configuration Register'),
	SymbolDescription('C1MCR14', 0xEFE0, 'CAN1 Message14 Control Register'),
	SymbolDescription('C1AR14', 0xEFE2, 'CAN1 Message14 Upper Arbitration Register'),
	SymbolDescription('C1LAR14', 0xEFE4, 'CAN1 Message14 Lower Arbitration Register'),
	SymbolDescription('C1MCFG14', 0xEFE6, 'CAN1 Message14 Configuration Register'),
	SymbolDescription('C1MCR15', 0xEFF0, 'CAN1 Message15 Control Register'),
	SymbolDescription('C1AR15', 0xEFF2, 'CAN1 Message15 Upper Arbitration Register'),
	SymbolDescription('C1LAR15', 0xEFF4, 'CAN1 Message15 Lower Arbitration Register'),
	SymbolDescription('C1MCFG15', 0xEFF6, 'CAN1 Message15 Configuration Register')
]
